local ServerScriptService = game:GetService('ServerScriptService')

local Benchmarker = require(ServerScriptService:WaitForChild("Benchmarker"))
wait(10)
local benchmark = Benchmarker.new(1e3, 2, true, true, true)
local benchmark2 = Benchmarker.new(1e3, 2, false, false, false)
print(benchmark:getAvg(math.floor, 10.4144))
--print(benchmark:getOperations(math.floor, 10.4144))
--print(Benchmarker:getOperations(math.floor, 10.4144))
--Benchmarker:benchmark(math.floor, 10.4144
benchmark:compare(math.floor, math.round, 1, 10.4144, 10.4144 )
print("######################")
benchmark2:compare(math.floor, math.round, 1, 10.4144, 10.4144 )
print("######################")
Benchmarker:compare(math.floor, math.round, 1, 10.4144, 10.4144 )